Update
jsahlen/todotxt pull request #9
Opened 2019-03-20 13:23 UTC by madeindjs

Dear @jsahlen ,

I just completely upgraded your gem (after 6 years of inactivity). I made theses actions:

- update Rake & Rspec (from 2.* to 3.*)
- update all Rspec tests with new syntax `expect(..).to eq ..`
- pass Rubocop parser on somes files to respect syntax conventions
- correct a failing text on  347df2b 

I hope you'll accept this PR cauz' I want to implement some new stuff on your library.

2019-04-02 10:52 UTC, madeindjs commented
@jsahlen , is this project alive?

2019-04-02 12:16 UTC, jsahlen commented
@madeindjs "Alive" is a strong word, but, yes! I'm grateful for your contribution, I just haven't had the time to have a thorough look yet—sorry.

2019-04-02 15:41 UTC, jsahlen requested changes
Thanks so much for this! I had some spelling- and language-related comments (and I'm aware some of the issues were there before your patches), but other than that, looks great!

2019-04-02 15:41 UTC, jsahlen commented on lib/todotxt.rb
> +# Todotxt is a Ruby librairy / CLI interface to work with a [todo.txt](http://www.todotxt.com) format.
```diff
- # Todotxt is a Ruby librairy / CLI interface to work with a [todo.txt](http://www.todotxt.com) format.
+ # Todotxt is a Ruby librairy / CLI interface to work with [todo.txt](http://www.todotxt.com) format files.
```

2019-04-02 15:41 UTC, jsahlen commented on lib/todotxt/cli.rb
> +          error_and_exit 'You are using an old config, which has no support for mulitple files. Please update your configuration.'
```diff
- You are using an old config, which has no support for mulitple files. Please update your configuration.
+ You are using an old config, which has no support for multiple files. Please update your configuration.
```

2019-04-02 15:41 UTC, jsahlen commented on lib/todotxt/todo.rb
> +  # Represent a task formated according
```diff
- Represent a task formated according
+ Represent a task formatted according to
```

2019-04-02 15:41 UTC, jsahlen commented on lib/todotxt/todo.rb
> +  # @attr [String] text reprensent all text definition of this task
```diff
- reprensent all text definition of this task
+ the complete text definition of this task
```

2019-04-02 15:41 UTC, jsahlen commented on lib/todotxt/todo.rb
> +  # @attr [Char] priority the letter who define pritority
```diff
- the letter who define pritority
+ the character which defines the task's priority
```

2019-04-02 15:41 UTC, jsahlen commented on lib/todotxt/todo.rb
> +    # Mark this task as undone
```diff
- Mark this task as undone
+ Mark this task as not done
```

2019-04-02 15:41 UTC, jsahlen commented on lib/todotxt/todo.rb
> +    # Add some content to the task
```diff
- Add some content to the task
+ Add some text to the end of this task definition
```

2019-04-02 15:41 UTC, jsahlen commented on lib/todotxt/todo.rb
> +    # Add some content to the task
```diff
- Add some content to the task
+ Add some text to the beginning of this task definition
```

2019-04-02 15:41 UTC, jsahlen commented on lib/todotxt/todo.rb
> +    # Compare another `Todo` according to their `line` and `priority` attribute.
```diff
- Compare another `Todo` according to their `line` and `priority` attribute.
+ Compare with another `Todo` based on `line` and `priority` attributes
```

2019-04-02 15:41 UTC, jsahlen commented on lib/todotxt/todo.rb
> +    end
👍

2019-04-02 15:41 UTC, jsahlen commented on lib/todotxt/todofile.rb
> +    attr_reader :path
👍

2019-04-02 15:41 UTC, jsahlen commented on lib/todotxt/todolist.rb
> +  # Represent a collection of `Todo`
```diff
- Represent a collection of `Todo`
+ Represent a collection of `Todo` items
```

2019-04-02 15:41 UTC, jsahlen commented on lib/todotxt/todolist.rb
> +    # Get all existing projects into todos
```diff
- Get all existing projects into todos
+ Get all projects from todo definitions
```

2019-04-02 15:41 UTC, jsahlen commented on lib/todotxt/todolist.rb
> +    # Get all existing contects into todos
```diff
- Get all existing contects into todos
+ Get all contexts from todo definitions
```

2019-04-03 10:47 UTC, madeindjs commented
@jsahlen , I made your proposed corrections in a5a9791

2019-04-09 07:37 UTC, jsahlen approved these changes

2019-04-09 07:37 UTC, merged

2019-04-09 07:41 UTC, jsahlen commented
@madeindjs Thanks! I've published the new version to RubyGems.org